/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PalavraArvoreCtrl;
import core.generic.Iterator;
import core.util.ArquivoIterator;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.PalavraNo;
import model.generic.No;

/**
 *
 * @author Marcelo
 */
public class PrincipalUI extends javax.swing.JFrame {

    private PalavraArvoreCtrl ctrl;

    /**
     * Creates new form PrincipalUI
     */
    public PrincipalUI() {
        initComponents();
        this.ctrl = new PalavraArvoreCtrl();
        this.setSize(600, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.initTable();
        this.ctrl.iniciaArvoreDoArquivo();
    }

    private void initTable() {
        this.tabela.setModel(new DefaultTableModel(
                new Object[][]{},
                new String[]{"Palavra", "Quantidade"}
        ) {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        }
        );

        this.tabela.getColumnModel().getColumn(0).setPreferredWidth(250);
        this.tabela.getColumnModel().getColumn(0).setResizable(false);

        this.tabela.getColumnModel().getColumn(1).setPreferredWidth(50);
        this.tabela.getColumnModel().getColumn(1).setResizable(false);

        this.tabela.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnCrescente = new javax.swing.JToggleButton();
        btnDecrescente = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrescente.setText("Mostrar Crescente");
        btnCrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrescenteActionPerformed(evt);
            }
        });

        btnDecrescente.setText("Mostrar Decrescente");
        btnDecrescente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecrescenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrescente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDecrescente)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrescente)
                    .addComponent(btnDecrescente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.setMaximumSize(null);
        tabela.setMinimumSize(null);
        tabela.setPreferredSize(null);
        jScrollPane2.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrescenteActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.tabela.getModel();
        dtm.setNumRows(0);
        this.ordemCrescente(this.ctrl.getArvore().getRaiz(), dtm);
    }//GEN-LAST:event_btnCrescenteActionPerformed

    private void btnDecrescenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecrescenteActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) this.tabela.getModel();
        dtm.setNumRows(0);
        this.ordemDecrescente(this.ctrl.getArvore().getRaiz(), dtm);
    }//GEN-LAST:event_btnDecrescenteActionPerformed

    private void ordemCrescente(No no, DefaultTableModel dtm) {
        if (no != null) {
            ordemCrescente(no.getNoEsquerdo(),dtm);
            dtm.addRow(new Object[]{((PalavraNo)no).getPalavra(),String.valueOf(((PalavraNo)no).getQuantidade())});
            ordemCrescente(no.getNoDireto(),dtm);
        }
    }
    
    private void ordemDecrescente(No no, DefaultTableModel dtm) {
        if (no != null) {
            ordemDecrescente(no.getNoDireto(),dtm);
            dtm.addRow(new Object[]{((PalavraNo)no).getPalavra(),String.valueOf(((PalavraNo)no).getQuantidade())});
            ordemDecrescente(no.getNoEsquerdo(),dtm);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCrescente;
    private javax.swing.JToggleButton btnDecrescente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
